In [34]:
import numpy as np


print("\nCREATE (Створення елементів)\n")

scalar = np.array(4)
print("Скаляр:", scalar)


vector = np.arange(1, 15)  
print("Вектор:", vector)

matrix = np.random.randint(1, 7, (3, 3)) 
print("Матриця:\n", matrix)



print("\n\nREAD (Читання елементів)\n")
print("Скаляр:", scalar)
print("Четвертий елемент вектора:", vector[3])
print("Елемент [1,2] матриці:", matrix[1, 2])



print("\n\nUPDATE (Оновлення елементів)\n")
scalar = 19
print("Новий скаляр:", scalar)

vector[2] = 25  
print("Оновлений вектор:", vector)

matrix[0, 0] = 10 
print("Оновлена матриця:\n", matrix)



print("\n\nDELETE (Видалення елементів)\n")
del scalar
try:
    print(scalar)
except NameError:
    print("Змінна 'scalar' справді видалена!")

vector = np.delete(vector, 1)  
print("Вектор після видалення:", vector)

matrix = np.delete(matrix, 1, axis=0)  
print("Матриця після видалення рядка:\n", matrix)

matrix = np.delete(matrix, 1, axis=1)  
print("Матриця після видалення стовпця:\n", matrix)



CREATE (Створення елементів)

Скаляр: 4
Вектор: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Матриця:
 [[6 3 5]
 [5 2 6]
 [1 3 6]]


READ (Читання елементів)

Скаляр: 4
Четвертий елемент вектора: 4
Елемент [1,2] матриці: 6


UPDATE (Оновлення елементів)

Новий скаляр: 19
Оновлений вектор: [ 1  2 25  4  5  6  7  8  9 10 11 12 13 14]
Оновлена матриця:
 [[10  3  5]
 [ 5  2  6]
 [ 1  3  6]]


DELETE (Видалення елементів)

Змінна 'scalar' справді видалена!
Вектор після видалення: [ 1 25  4  5  6  7  8  9 10 11 12 13 14]
Матриця після видалення рядка:
 [[10  3  5]
 [ 1  3  6]]
Матриця після видалення стовпця:
 [[10  5]
 [ 1  6]]
